# Generated by Django 5.1.4 on 2024-12-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanction',
            name='recordId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanctionedentity',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sanctionedentity',
            name='sanctionId',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='sanctionedentity',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
