# Generated by Django 5.1.4 on 2024-12-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='sanctionedEntity',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='debt',
            old_name='sanctionedEntity',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='passport',
            old_name='sanctionedEntity',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='sanctionedEntity',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='representation',
            old_name='sanctionedEntity',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='unknownlink',
            old_name='sanctionedEntity',
            new_name='entity',
        ),
    ]
