# Generated by Django 5.1.4 on 2025-01-28 12:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_alter_sanction_recordid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Address"},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "Person"},
        ),
        migrations.CreateModel(
            name="BatchUpload",
            fields=[
                (
                    "batch_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("success_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="data_batchu_status_50f0c4_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="data_batchu_created_d1ae08_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BatchError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="data.batchupload",
                    ),
                ),
            ],
            options={
                "ordering": ["line_number"],
            },
        ),
    ]
