# Generated by Django 5.1.4 on 2025-05-22 12:03

import data.amlmodels.customer_models
import data.amlmodels.profile_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_alter_address_options_alter_person_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("SEARCH", "Search"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILURE", "Failure")],
                        default="SUCCESS",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activity Logs",
                "db_table": "activity_logs",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=50, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("tax_id", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=data.amlmodels.customer_models.customer_photo_path,
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Customers",
                "db_table": "customers",
            },
        ),
        migrations.CreateModel(
            name="BusinessInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        blank=True,
                        choices=[("corporation", "Corporation")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("regi_number", models.CharField(blank=True, max_length=50, null=True)),
                ("incorporation_date", models.DateField(blank=True, null=True)),
                (
                    "incorporation_country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bd", "Bangladesh"),
                            ("usa", "United States of America"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "registered_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "operational_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=50, unique=True)),
                ("website", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "industry_sector",
                    models.CharField(
                        blank=True,
                        choices=[("it", "Information Technology")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "key_products_services",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("business_activities_desc", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_info",
                        to="data.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Business Information",
                "db_table": "business_info",
            },
        ),
        migrations.CreateModel(
            name="BankInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[("savings", "Savings"), ("checking", "Checking")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "swift_code_iban",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_info",
                        to="data.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bank Information",
                "db_table": "bank_info",
            },
        ),
        migrations.CreateModel(
            name="CustomerAdditionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_purpose",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "expected_transactions",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "annual_turnover",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "fund_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pep_status",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_addi_info",
                        to="data.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Customer Additional Information",
                "db_table": "customer_addi_info",
            },
        ),
        migrations.CreateModel(
            name="Employability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employed", "Employed"),
                            ("self_employed", "Self-Employed"),
                            ("unemployed", "Unemployed"),
                            ("retired", "Retired"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "employer_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "employer_address",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "annual_income",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employabilities",
                        to="data.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employability",
                "db_table": "employabilities",
            },
        ),
        migrations.CreateModel(
            name="FlagApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=50)),
                (
                    "reason_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("suspicious_activity", "Suspicious Activity"),
                            ("unusual_transaction", "Unusual Transaction"),
                            ("high_risk_country", "High Risk Country"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("details", models.TextField(blank=True, null=True)),
                (
                    "forwarded_to",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("forward_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flag_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Flag & Approval",
                "db_table": "flag_approvals",
            },
        ),
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("passport", "Passport"),
                            ("driving_license", "Driver's License"),
                            ("nid", "National ID"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("id_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "issuing_country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bd", "Bangladesh"),
                            ("usa", "United States of America"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=data.amlmodels.customer_models.customer_document_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to="data.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Identities",
                "db_table": "identities",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("organization", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=data.amlmodels.profile_model.user_photo_path,
                    ),
                ),
                ("two_fa_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.CreateModel(
            name="ResearchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(blank=True, max_length=20, null=True)),
                ("document", models.JSONField(default=list)),
                ("status", models.CharField(blank=True, max_length=50)),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "research_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("external_data_source", "External Data Source"),
                            ("transaction_analysis", "Transaction Analysis"),
                            ("customer_profile", "Customer Profile"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Research Request",
                "db_table": "research_requests",
            },
        ),
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("passport", "Passport"),
                            ("driving_license", "Driver's License"),
                            ("nid", "National ID"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("document", models.JSONField(default=list)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Verifications",
                "db_table": "verifications",
            },
        ),
    ]
