# Generated by Django 5.1.4 on 2025-05-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_activitylogs_customer_businessinfo_bankinfo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flagapproval",
            name="customer_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
