# Generated by Django 5.1.4 on 2025-06-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_searchhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="failed_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="success_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
