# Generated by Django 5.1.4 on 2025-06-01 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_customer_failed_attempts_customer_is_flagged_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AmlService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                (
                    "service_category",
                    models.CharField(
                        choices=[
                            ("aml", "AML Screening"),
                            ("idv", "Identity Verification"),
                            ("kyb", "Know Your Business"),
                            ("investor_verification", "Investor Verification"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_declined", models.BooleanField(default=False)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aml_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "AML Services",
                "db_table": "aml_services",
            },
        ),
    ]
