# Generated by Django 5.1.4 on 2025-06-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_amlservice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amlservice",
            name="is_declined",
        ),
        migrations.RemoveField(
            model_name="amlservice",
            name="is_verified",
        ),
    ]
