# Generated by Django 5.1.4 on 2025-06-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0009_remove_amlservice_is_declined_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="service_id",
            field=models.IntegerField(default=0),
        ),
    ]
