# Generated by Django 5.1.4 on 2025-06-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_verification_service_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
