# Generated by Django 5.1.4 on 2025-06-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0012_verification_country_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="reference_id",
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
