# Generated by Django 5.1.4 on 2025-06-02 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0013_verification_reference_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("browser", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "browser_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("os", models.CharField(blank=True, max_length=100, null=True)),
                ("device", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="data.verification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Metadata",
                "verbose_name_plural": "Verification Metadata",
            },
        ),
    ]
