# Generated by Django 5.1.4 on 2025-06-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0015_verificationtimeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="is_manual_review",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this verification requires manual review",
            ),
        ),
    ]
