# Generated by Django 5.1.4 on 2025-06-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0016_verification_is_manual_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylogs",
            name="location",
        ),
        migrations.AddField(
            model_name="activitylogs",
            name="browser",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="activitylogs",
            name="browser_version",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="activitylogs",
            name="city",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="activitylogs",
            name="country",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="activitylogs",
            name="device",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="activitylogs",
            name="os",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="activitylogs",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
