# Generated by Django 5.1.4 on 2025-06-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_remove_activitylogs_location_activitylogs_browser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verification_id", models.IntegerField()),
                (
                    "screening_models",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("is_found", models.BooleanField(default=False)),
                ("found_models", models.JSONField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Verification Info",
                "verbose_name_plural": "Verification Info",
            },
        ),
    ]
