# Generated by Django 5.1.4 on 2025-06-15 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0020_templatetitle_templatepage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templatepage",
            name="answer_type",
        ),
        migrations.RemoveField(
            model_name="templatepage",
            name="description",
        ),
        migrations.RemoveField(
            model_name="templatepage",
            name="options",
        ),
        migrations.RemoveField(
            model_name="templatepage",
            name="question",
        ),
        migrations.RemoveField(
            model_name="templatepage",
            name="required",
        ),
        migrations.CreateModel(
            name="TemplateQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("answer_type", models.CharField(max_length=50)),
                ("required", models.BooleanField(default=False)),
                ("options", models.JSONField(blank=True, null=True)),
                ("description_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="data.templatepage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Template Questions",
                "db_table": "template_questions",
            },
        ),
    ]
