# Generated by Django 5.1.4 on 2025-06-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0021_remove_templatepage_answer_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="template_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
