# Generated by Django 5.1.4 on 2025-06-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0022_verification_template_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatequestion",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="templatequestion",
            name="description_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
