# Generated by Django 5.1.4 on 2025-06-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0023_alter_templatequestion_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="template_answers",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
