# Generated by Django 5.1.4 on 2025-06-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0024_verification_template_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="document_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="verification",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verification",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="verification",
            name="id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("passport", "Passport"),
                    ("nid", "National ID"),
                    ("driving_license", "Driver's License"),
                    ("utility_bill", "Utility Bill"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
