# Generated by Django 5.1.4 on 2025-06-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0025_verification_document_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="registration_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="verification",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
