# Generated by Django 5.1.4 on 2025-06-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0026_customer_registration_number_verification_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="verification_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
