# Generated by Django 5.1.4 on 2025-06-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0028_bulkamlscreening_bulkamlscreeningrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="registration_number",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="tax_id",
        ),
    ]
