# Generated by Django 5.1.4 on 2025-06-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0029_remove_customer_registration_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="registration_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="verification",
            name="tax_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="verification",
            name="vat_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
