# Generated by Django 5.1.4 on 2025-06-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0030_verification_registration_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="extract_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="verification",
            name="id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("passport", "Passport"),
                    ("nid", "National ID"),
                    ("driving_license", "Driver's License"),
                    ("utility_bill", "Utility Bill"),
                    ("kyb_document", "Kyb Document"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
